#!/bin/sh

if [ ! -x $(command -v autoreconf) ]; then
	echo "No executable autoreconf binary found!";
	exit 1;
fi

autoreconf -ifv

if [ $? != 0 ]; then
	echo "error reconfiguring";
	exit 1;
fi

if [ ! -f configure ]; then
	echo "no configuration found";
	exit 1;
fi

./configure $@

exit $?;
